import importlib

import pytest

MODULES = [
    "main",
    "backend.app.main",
    "backend.app.agents.builders.graphs_builder",
    "backend.app.agents.executors.invoice_pipeline",
    "backend.app.agents.nodes.approval",
    "backend.app.agents.nodes.extraction",
    "backend.app.agents.nodes.payment",
    "backend.app.agents.nodes.review",
    "backend.app.agents.nodes.shared",
    "backend.app.agents.nodes.validation",
    "backend.app.api.v1.router",
    "backend.app.bootstrap.application",
    "backend.app.bootstrap.invoice_runtime",
    "backend.app.cli.renderers",
    "backend.app.core.config",
    "backend.app.domain.policies",
    "backend.app.domain.validation",
    "backend.app.infrastructure.db.session",
    "backend.app.infrastructure.db.models",
    "backend.app.infrastructure.db.models.agent_runs",
    "backend.app.infrastructure.db.models.base",
    "backend.app.infrastructure.db.models.catalog",
    "backend.app.infrastructure.db.models.events",
    "backend.app.infrastructure.db.models.payments",
    "backend.app.infrastructure.db.models.results",
    "backend.app.infrastructure.db.repositories.inventory",
    "backend.app.infrastructure.db.repositories.payments",
    "backend.app.infrastructure.db.repositories.runs",
    "backend.app.infrastructure.documents",
    "backend.app.infrastructure.graph.provider",
    "backend.app.infrastructure.graph.runner",
    "backend.app.infrastructure.llm.factory",
    "backend.app.infrastructure.queue.celery_dispatcher",
    "backend.app.ports.providers",
    "backend.app.ports.queue",
    "backend.app.ports.repositories",
    "backend.app.schemas.errors",
    "backend.app.schemas.invoice",
    "backend.app.schemas.payment",
    "backend.app.schemas.review",
    "backend.app.schemas.runs",
    "backend.app.schemas.workflow",
    "backend.app.services.invoice_execution",
    "backend.app.services.invoice_intake",
    "backend.app.services.run_application",
    "backend.app.services.invoice_reviews",
    "backend.app.services.run_queries",
    "backend.app.workers.app",
    "backend.app.workers.tasks",
]


@pytest.mark.parametrize("module_name", MODULES)
def test_backend_module_imports(module_name: str) -> None:
    assert importlib.import_module(module_name) is not None
