/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Run */
        post: operations["review_run_api_v1_runs__run_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalRecommendation */
        ApprovalRecommendation: {
            /**
             * Decided By
             * @default agent
             * @enum {string}
             */
            decided_by: "agent" | "policy";
            final_route: components["schemas"]["DecisionRoute"];
            proposed_route: components["schemas"]["DecisionRoute"];
            /** Reason Codes */
            reason_codes?: string[];
            /**
             * Reflection Count
             * @default 0
             */
            reflection_count: number;
            /** Summary */
            summary: string;
        };
        /** Body_create_run_api_v1_runs_post */
        Body_create_run_api_v1_runs_post: {
            /** File */
            file: string;
        };
        /**
         * DecisionRoute
         * @enum {string}
         */
        DecisionRoute: "approve" | "review" | "reject";
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Run Id */
            run_id?: string | null;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "info" | "warning" | "blocking";
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** HumanReview */
        HumanReview: {
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Reason */
            reason: string;
            /**
             * Resume Pending
             * @default true
             */
            resume_pending: boolean;
        };
        /** InvoiceData */
        InvoiceData: {
            /** Currency */
            currency?: string | null;
            /** Due Date */
            due_date?: string | null;
            /**
             * Extraction Confidence
             * @default high
             * @enum {string}
             */
            extraction_confidence: "high" | "medium" | "low";
            /** Invoice Date */
            invoice_date?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Items */
            items?: components["schemas"]["InvoiceItem"][];
            /** Payment Terms */
            payment_terms?: string | null;
            /** Revision */
            revision?: string | null;
            shipping?: components["schemas"]["Money"] | null;
            subtotal?: components["schemas"]["Money"] | null;
            tax?: components["schemas"]["Money"] | null;
            total?: components["schemas"]["Money"] | null;
            /** Vendor Name */
            vendor_name?: string | null;
        };
        /** InvoiceItem */
        InvoiceItem: {
            /** Line Number */
            line_number: number;
            line_total?: components["schemas"]["Money"] | null;
            /** Normalized Item Code */
            normalized_item_code?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Source Name */
            source_name?: string | null;
            unit_price?: components["schemas"]["Money"] | null;
        };
        /** Money */
        Money: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
        };
        /** PaymentResult */
        PaymentResult: {
            amount: components["schemas"]["Money"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Mock Reference */
            mock_reference?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "succeeded" | "failed";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Reason */
            reason: string;
        };
        /** RunCreationResponse */
        RunCreationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deduplicated */
            deduplicated: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source Filename */
            source_filename: string;
            stage: components["schemas"]["RunStage"];
            status: components["schemas"]["RunStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunDetail */
        RunDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            error?: components["schemas"]["WorkflowError"] | null;
            /** Events */
            events?: components["schemas"]["RunEvent"][];
            /** Findings */
            findings?: components["schemas"]["ValidationFinding"][];
            invoice?: components["schemas"]["InvoiceData"] | null;
            payment?: components["schemas"]["PaymentResult"] | null;
            recommendation?: components["schemas"]["ApprovalRecommendation"] | null;
            review?: components["schemas"]["HumanReview"] | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source Filename */
            source_filename: string;
            stage: components["schemas"]["RunStage"];
            status: components["schemas"]["RunStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunEvent */
        RunEvent: {
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Event Id */
            event_id: number;
            /** Message */
            message: string;
            stage: components["schemas"]["RunStage"];
            status: components["schemas"]["RunStatus"];
        };
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
        };
        /**
         * RunStage
         * @enum {string}
         */
        RunStage: "ingest" | "extract" | "validate" | "recommend" | "review" | "pay" | "finalize";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "review_required" | "completed" | "rejected" | "failed";
        /** RunSummary */
        RunSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source Filename */
            source_filename: string;
            stage: components["schemas"]["RunStage"];
            status: components["schemas"]["RunStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationFinding */
        ValidationFinding: {
            /** Actual */
            actual?: unknown | null;
            /** Code */
            code: string;
            /** Expected */
            expected?: unknown | null;
            /** Field Path */
            field_path?: string | null;
            /** Item Line Number */
            item_line_number?: number | null;
            /** Message */
            message: string;
            severity: components["schemas"]["FindingSeverity"];
        };
        /** WorkflowError */
        WorkflowError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_run_api_v1_runs_post"];
            };
        };
        responses: {
            /** @description Deduplicated run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreationResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    review_run_api_v1_runs__run_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
